
project_id = "sxrinuxxlmytddymjbmr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://knowledge-manager-02.lovable.app"

[auth.email]
enabled = true
double_confirm_changes = true
enable_confirmations = true

[analytics]
enabled = false
port = 54327
vector_port = 54328

[experimental]
multiservice = false

[[functions]]
verify_jwt = true
name = "verify-openai-key"

[[functions]]
verify_jwt = true
name = "verify-cohere-key"

[[functions]]
verify_jwt = true
name = "verify-huggingface-key"

[[functions]]
verify_jwt = true
name = "verify-anthropic-key"

[[functions]]
verify_jwt = true
name = "chat-completion"

[[functions]]
verify_jwt = true
name = "create-user"

[[functions]]
verify_jwt = false
name = "send-welcome-email"
